//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.1.0.0
//     Timestamp      : 26/2/2020 13:51:32
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
PUBLIC PARTIAL CLASS UAlertForm ;
    INHERIT System.Windows.Forms.Form
    PRIVATE splitContainerControl1 AS DevExpress.XtraEditors.SplitContainerControl
    PRIVATE sBarDockControlAlerts AS DevExpress.XtraBars.StandaloneBarDockControl
    PRIVATE barManager1 AS DevExpress.XtraBars.BarManager
    PRIVATE barAlerts AS DevExpress.XtraBars.Bar
    PRIVATE barButtonItem1 AS DevExpress.XtraBars.BarButtonItem
    PRIVATE barButtonItem2 AS DevExpress.XtraBars.BarButtonItem
    PRIVATE barButtonItem3 AS DevExpress.XtraBars.BarButtonItem
    PRIVATE barConditions AS DevExpress.XtraBars.Bar
    PRIVATE barButtonItem4 AS DevExpress.XtraBars.BarButtonItem
    PRIVATE barButtonItem5 AS DevExpress.XtraBars.BarButtonItem
    PRIVATE barButtonItem6 AS DevExpress.XtraBars.BarButtonItem
    PRIVATE barDockControlTop AS DevExpress.XtraBars.BarDockControl
    PRIVATE barDockControlBottom AS DevExpress.XtraBars.BarDockControl
    PRIVATE barDockControlLeft AS DevExpress.XtraBars.BarDockControl
    PRIVATE barDockControlRight AS DevExpress.XtraBars.BarDockControl
    PRIVATE splitContainerControl2 AS DevExpress.XtraEditors.SplitContainerControl
    PRIVATE sBarDockControlConditions AS DevExpress.XtraBars.StandaloneBarDockControl
    PRIVATE barAndDockingController1 AS DevExpress.XtraBars.BarAndDockingController
    PRIVATE GridAlerts AS DevExpress.XtraGrid.GridControl
    PRIVATE GridViewAlerts AS DevExpress.XtraGrid.Views.Grid.GridView
    PRIVATE GridConditions AS DevExpress.XtraGrid.GridControl
    PRIVATE GridViewConditions AS DevExpress.XtraGrid.Views.Grid.GridView
    PRIVATE TreeListVessels AS DevExpress.XtraTreeList.TreeList
    PRIVATE barButtonItem7 AS DevExpress.XtraBars.BarButtonItem
    PRIVATE components := NULL AS System.ComponentModel.IContainer
                                                                                                                                            
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != NULL))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
    PRIVATE METHOD InitializeComponent() AS VOID STRICT
        SELF:components := System.ComponentModel.Container{}
        LOCAL resources := System.ComponentModel.ComponentResourceManager{TYPEOF(UAlertForm)} AS System.ComponentModel.ComponentResourceManager
        SELF:splitContainerControl1 := DevExpress.XtraEditors.SplitContainerControl{}
        SELF:GridAlerts := DevExpress.XtraGrid.GridControl{}
        SELF:GridViewAlerts := DevExpress.XtraGrid.Views.Grid.GridView{}
        SELF:barManager1 := DevExpress.XtraBars.BarManager{SELF:components}
        SELF:barAlerts := DevExpress.XtraBars.Bar{}
        SELF:barButtonItem1 := DevExpress.XtraBars.BarButtonItem{}
        SELF:barButtonItem3 := DevExpress.XtraBars.BarButtonItem{}
        SELF:barButtonItem7 := DevExpress.XtraBars.BarButtonItem{}
        SELF:sBarDockControlAlerts := DevExpress.XtraBars.StandaloneBarDockControl{}
        SELF:barConditions := DevExpress.XtraBars.Bar{}
        SELF:barButtonItem4 := DevExpress.XtraBars.BarButtonItem{}
        SELF:barButtonItem6 := DevExpress.XtraBars.BarButtonItem{}
        SELF:sBarDockControlConditions := DevExpress.XtraBars.StandaloneBarDockControl{}
        SELF:barAndDockingController1 := DevExpress.XtraBars.BarAndDockingController{SELF:components}
        SELF:barDockControlTop := DevExpress.XtraBars.BarDockControl{}
        SELF:barDockControlBottom := DevExpress.XtraBars.BarDockControl{}
        SELF:barDockControlLeft := DevExpress.XtraBars.BarDockControl{}
        SELF:barDockControlRight := DevExpress.XtraBars.BarDockControl{}
        SELF:barButtonItem2 := DevExpress.XtraBars.BarButtonItem{}
        SELF:barButtonItem5 := DevExpress.XtraBars.BarButtonItem{}
        SELF:splitContainerControl2 := DevExpress.XtraEditors.SplitContainerControl{}
        SELF:TreeListVessels := DevExpress.XtraTreeList.TreeList{}
        SELF:GridConditions := DevExpress.XtraGrid.GridControl{}
        SELF:GridViewConditions := DevExpress.XtraGrid.Views.Grid.GridView{}
        ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl1)):BeginInit()
        SELF:splitContainerControl1:SuspendLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:GridAlerts)):BeginInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:GridViewAlerts)):BeginInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:barManager1)):BeginInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:barAndDockingController1)):BeginInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl2)):BeginInit()
        SELF:splitContainerControl2:SuspendLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:TreeListVessels)):BeginInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:GridConditions)):BeginInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:GridViewConditions)):BeginInit()
        SELF:SuspendLayout()
        // 
        // splitContainerControl1
        // 
        SELF:splitContainerControl1:Dock := System.Windows.Forms.DockStyle.Fill
        SELF:splitContainerControl1:Horizontal := false
        SELF:splitContainerControl1:Location := System.Drawing.Point{0, 0}
        SELF:splitContainerControl1:Name := "splitContainerControl1"
        SELF:splitContainerControl1:Panel1:Controls:Add(SELF:GridAlerts)
        SELF:splitContainerControl1:Panel1:Controls:Add(SELF:sBarDockControlAlerts)
        SELF:splitContainerControl1:Panel1:Text := "Panel1"
        SELF:splitContainerControl1:Panel2:Controls:Add(SELF:splitContainerControl2)
        SELF:splitContainerControl1:Panel2:Text := "Panel2"
        SELF:splitContainerControl1:Size := System.Drawing.Size{953, 560}
        SELF:splitContainerControl1:SplitterPosition := 260
        SELF:splitContainerControl1:TabIndex := 0
        SELF:splitContainerControl1:Text := "splitContainerControl1"
        // 
        // GridAlerts
        // 
        SELF:GridAlerts:Dock := System.Windows.Forms.DockStyle.Fill
        SELF:GridAlerts:Location := System.Drawing.Point{0, 28}
        SELF:GridAlerts:MainView := SELF:GridViewAlerts
        SELF:GridAlerts:MenuManager := SELF:barManager1
        SELF:GridAlerts:Name := "GridAlerts"
        SELF:GridAlerts:Size := System.Drawing.Size{953, 232}
        SELF:GridAlerts:TabIndex := 1
        SELF:GridAlerts:ViewCollection:AddRange(<DevExpress.XtraGrid.Views.Base.BaseView>{ SELF:GridViewAlerts })
        // 
        // GridViewAlerts
        // 
        SELF:GridViewAlerts:GridControl := SELF:GridAlerts
        SELF:GridViewAlerts:Name := "GridViewAlerts"
        SELF:GridViewAlerts:OptionsCustomization:AllowFilter := false
        SELF:GridViewAlerts:OptionsCustomization:AllowGroup := false
        SELF:GridViewAlerts:OptionsView:RowAutoHeight := true
        SELF:GridViewAlerts:OptionsView:ShowGroupPanel := false
        SELF:GridViewAlerts:OptionsView:ShowIndicator := false
        SELF:GridViewAlerts:FocusedRowChanged += DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventHandler{ SELF, @GridViewAlerts_FocusedRowChanged() }
        SELF:GridViewAlerts:CellValueChanged += DevExpress.XtraGrid.Views.Base.CellValueChangedEventHandler{ SELF, @GridViewAlerts_CellValueChanged() }
        SELF:GridViewAlerts:CustomUnboundColumnData += DevExpress.XtraGrid.Views.Base.CustomColumnDataEventHandler{ SELF, @GridViewAlerts_CustomUnboundColumnData() }
        // 
        // barManager1
        // 
        SELF:barManager1:Bars:AddRange(<DevExpress.XtraBars.Bar>{ SELF:barAlerts, SELF:barConditions })
        SELF:barManager1:Controller := SELF:barAndDockingController1
        SELF:barManager1:DockControls:Add(SELF:barDockControlTop)
        SELF:barManager1:DockControls:Add(SELF:barDockControlBottom)
        SELF:barManager1:DockControls:Add(SELF:barDockControlLeft)
        SELF:barManager1:DockControls:Add(SELF:barDockControlRight)
        SELF:barManager1:DockControls:Add(SELF:sBarDockControlAlerts)
        SELF:barManager1:DockControls:Add(SELF:sBarDockControlConditions)
        SELF:barManager1:Form := SELF
        SELF:barManager1:Items:AddRange(<DevExpress.XtraBars.BarItem>{ SELF:barButtonItem1, SELF:barButtonItem2, SELF:barButtonItem3, SELF:barButtonItem4, SELF:barButtonItem5, SELF:barButtonItem6, SELF:barButtonItem7 })
        SELF:barManager1:MaxItemId := 7
        // 
        // barAlerts
        // 
        SELF:barAlerts:BarName := "AlertsMenu"
        SELF:barAlerts:DockCol := 0
        SELF:barAlerts:DockRow := 0
        SELF:barAlerts:DockStyle := DevExpress.XtraBars.BarDockStyle.Standalone
        SELF:barAlerts:LinksPersistInfo:AddRange(<DevExpress.XtraBars.LinkPersistInfo>{ DevExpress.XtraBars.LinkPersistInfo{SELF:barButtonItem1}, DevExpress.XtraBars.LinkPersistInfo{SELF:barButtonItem3}, DevExpress.XtraBars.LinkPersistInfo{SELF:barButtonItem7} })
        SELF:barAlerts:OptionsBar:AllowQuickCustomization := false
        SELF:barAlerts:OptionsBar:AllowRename := true
        SELF:barAlerts:OptionsBar:UseWholeRow := true
        SELF:barAlerts:StandaloneBarDockControl := SELF:sBarDockControlAlerts
        SELF:barAlerts:Text := "AlertsMenu"
        // 
        // barButtonItem1
        // 
        SELF:barButtonItem1:Caption := "New"
        SELF:barButtonItem1:Id := 0
        SELF:barButtonItem1:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("barButtonItem1.ImageOptions.Image")))
        SELF:barButtonItem1:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("barButtonItem1.ImageOptions.LargeImage")))
        SELF:barButtonItem1:Name := "barButtonItem1"
        SELF:barButtonItem1:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @barButtonItem1_ItemClick() }
        // 
        // barButtonItem3
        // 
        SELF:barButtonItem3:Caption := "Delete"
        SELF:barButtonItem3:Id := 2
        SELF:barButtonItem3:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("barButtonItem3.ImageOptions.Image")))
        SELF:barButtonItem3:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("barButtonItem3.ImageOptions.LargeImage")))
        SELF:barButtonItem3:Name := "barButtonItem3"
        SELF:barButtonItem3:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @barButtonItem3_ItemClick() }
        // 
        // barButtonItem7
        // 
        SELF:barButtonItem7:Caption := "Check Package"
        SELF:barButtonItem7:Id := 6
        SELF:barButtonItem7:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("barButtonItem7.ImageOptions.Image")))
        SELF:barButtonItem7:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("barButtonItem7.ImageOptions.LargeImage")))
        SELF:barButtonItem7:Name := "barButtonItem7"
        SELF:barButtonItem7:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @barButtonItem7_ItemClick() }
        // 
        // sBarDockControlAlerts
        // 
        SELF:sBarDockControlAlerts:CausesValidation := false
        SELF:sBarDockControlAlerts:Dock := System.Windows.Forms.DockStyle.Top
        SELF:sBarDockControlAlerts:Location := System.Drawing.Point{0, 0}
        SELF:sBarDockControlAlerts:Manager := SELF:barManager1
        SELF:sBarDockControlAlerts:Name := "sBarDockControlAlerts"
        SELF:sBarDockControlAlerts:Size := System.Drawing.Size{953, 28}
        SELF:sBarDockControlAlerts:Text := "standaloneBarDockControl2"
        // 
        // barConditions
        // 
        SELF:barConditions:BarName := "ConditionsMenu"
        SELF:barConditions:DockCol := 0
        SELF:barConditions:DockRow := 0
        SELF:barConditions:DockStyle := DevExpress.XtraBars.BarDockStyle.Standalone
        SELF:barConditions:LinksPersistInfo:AddRange(<DevExpress.XtraBars.LinkPersistInfo>{ DevExpress.XtraBars.LinkPersistInfo{SELF:barButtonItem4}, DevExpress.XtraBars.LinkPersistInfo{SELF:barButtonItem6} })
        SELF:barConditions:OptionsBar:AllowQuickCustomization := false
        SELF:barConditions:OptionsBar:AllowRename := true
        SELF:barConditions:OptionsBar:UseWholeRow := true
        SELF:barConditions:StandaloneBarDockControl := SELF:sBarDockControlConditions
        SELF:barConditions:Text := "ConditionsMenu"
        // 
        // barButtonItem4
        // 
        SELF:barButtonItem4:Caption := "New"
        SELF:barButtonItem4:Id := 3
        SELF:barButtonItem4:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("barButtonItem4.ImageOptions.Image")))
        SELF:barButtonItem4:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("barButtonItem4.ImageOptions.LargeImage")))
        SELF:barButtonItem4:Name := "barButtonItem4"
        SELF:barButtonItem4:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @barButtonItem4_ItemClick() }
        // 
        // barButtonItem6
        // 
        SELF:barButtonItem6:Caption := "Delete"
        SELF:barButtonItem6:Id := 5
        SELF:barButtonItem6:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("barButtonItem6.ImageOptions.Image")))
        SELF:barButtonItem6:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("barButtonItem6.ImageOptions.LargeImage")))
        SELF:barButtonItem6:Name := "barButtonItem6"
        SELF:barButtonItem6:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @barButtonItem6_ItemClick() }
        // 
        // sBarDockControlConditions
        // 
        SELF:sBarDockControlConditions:CausesValidation := false
        SELF:sBarDockControlConditions:Dock := System.Windows.Forms.DockStyle.Top
        SELF:sBarDockControlConditions:Location := System.Drawing.Point{0, 0}
        SELF:sBarDockControlConditions:Manager := SELF:barManager1
        SELF:sBarDockControlConditions:Name := "sBarDockControlConditions"
        SELF:sBarDockControlConditions:Size := System.Drawing.Size{726, 28}
        SELF:sBarDockControlConditions:Text := "standaloneBarDockControl1"
        // 
        // barAndDockingController1
        // 
        SELF:barAndDockingController1:PropertiesBar:AllowLinkLighting := false
        SELF:barAndDockingController1:PropertiesBar:DefaultGlyphSize := System.Drawing.Size{16, 16}
        SELF:barAndDockingController1:PropertiesBar:DefaultLargeGlyphSize := System.Drawing.Size{32, 32}
        // 
        // barDockControlTop
        // 
        SELF:barDockControlTop:CausesValidation := false
        SELF:barDockControlTop:Dock := System.Windows.Forms.DockStyle.Top
        SELF:barDockControlTop:Location := System.Drawing.Point{0, 0}
        SELF:barDockControlTop:Manager := SELF:barManager1
        SELF:barDockControlTop:Size := System.Drawing.Size{953, 0}
        // 
        // barDockControlBottom
        // 
        SELF:barDockControlBottom:CausesValidation := false
        SELF:barDockControlBottom:Dock := System.Windows.Forms.DockStyle.Bottom
        SELF:barDockControlBottom:Location := System.Drawing.Point{0, 560}
        SELF:barDockControlBottom:Manager := SELF:barManager1
        SELF:barDockControlBottom:Size := System.Drawing.Size{953, 0}
        // 
        // barDockControlLeft
        // 
        SELF:barDockControlLeft:CausesValidation := false
        SELF:barDockControlLeft:Dock := System.Windows.Forms.DockStyle.Left
        SELF:barDockControlLeft:Location := System.Drawing.Point{0, 0}
        SELF:barDockControlLeft:Manager := SELF:barManager1
        SELF:barDockControlLeft:Size := System.Drawing.Size{0, 560}
        // 
        // barDockControlRight
        // 
        SELF:barDockControlRight:CausesValidation := false
        SELF:barDockControlRight:Dock := System.Windows.Forms.DockStyle.Right
        SELF:barDockControlRight:Location := System.Drawing.Point{953, 0}
        SELF:barDockControlRight:Manager := SELF:barManager1
        SELF:barDockControlRight:Size := System.Drawing.Size{0, 560}
        // 
        // barButtonItem2
        // 
        SELF:barButtonItem2:Caption := "Edit"
        SELF:barButtonItem2:Id := 1
        SELF:barButtonItem2:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("barButtonItem2.ImageOptions.Image")))
        SELF:barButtonItem2:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("barButtonItem2.ImageOptions.LargeImage")))
        SELF:barButtonItem2:Name := "barButtonItem2"
        // 
        // barButtonItem5
        // 
        SELF:barButtonItem5:Caption := "Edit"
        SELF:barButtonItem5:Id := 4
        SELF:barButtonItem5:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("barButtonItem5.ImageOptions.Image")))
        SELF:barButtonItem5:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("barButtonItem5.ImageOptions.LargeImage")))
        SELF:barButtonItem5:Name := "barButtonItem5"
        // 
        // splitContainerControl2
        // 
        SELF:splitContainerControl2:Dock := System.Windows.Forms.DockStyle.Fill
        SELF:splitContainerControl2:Location := System.Drawing.Point{0, 0}
        SELF:splitContainerControl2:Name := "splitContainerControl2"
        SELF:splitContainerControl2:Panel1:Controls:Add(SELF:TreeListVessels)
        SELF:splitContainerControl2:Panel1:Text := "Panel1"
        SELF:splitContainerControl2:Panel2:Controls:Add(SELF:GridConditions)
        SELF:splitContainerControl2:Panel2:Controls:Add(SELF:sBarDockControlConditions)
        SELF:splitContainerControl2:Panel2:Text := "Panel2"
        SELF:splitContainerControl2:Size := System.Drawing.Size{953, 295}
        SELF:splitContainerControl2:SplitterPosition := 222
        SELF:splitContainerControl2:TabIndex := 1
        SELF:splitContainerControl2:Text := "splitContainerControl2"
        // 
        // TreeListVessels
        // 
        SELF:TreeListVessels:BorderStyle := DevExpress.XtraEditors.Controls.BorderStyles.Flat
        SELF:TreeListVessels:Dock := System.Windows.Forms.DockStyle.Fill
        SELF:TreeListVessels:Location := System.Drawing.Point{0, 0}
        SELF:TreeListVessels:Name := "TreeListVessels"
        SELF:TreeListVessels:OptionsView:ShowColumns := false
        SELF:TreeListVessels:OptionsView:ShowHorzLines := false
        SELF:TreeListVessels:OptionsView:ShowIndicator := false
        SELF:TreeListVessels:Size := System.Drawing.Size{222, 295}
        SELF:TreeListVessels:TabIndex := 0
        SELF:TreeListVessels:AfterCheckNode += DevExpress.XtraTreeList.NodeEventHandler{ SELF, @TreeListVessels_AfterCheckNode() }
        // 
        // GridConditions
        // 
        SELF:GridConditions:Dock := System.Windows.Forms.DockStyle.Fill
        SELF:GridConditions:Location := System.Drawing.Point{0, 28}
        SELF:GridConditions:MainView := SELF:GridViewConditions
        SELF:GridConditions:MenuManager := SELF:barManager1
        SELF:GridConditions:Name := "GridConditions"
        SELF:GridConditions:Size := System.Drawing.Size{726, 267}
        SELF:GridConditions:TabIndex := 1
        SELF:GridConditions:ViewCollection:AddRange(<DevExpress.XtraGrid.Views.Base.BaseView>{ SELF:GridViewConditions })
        // 
        // GridViewConditions
        // 
        SELF:GridViewConditions:GridControl := SELF:GridConditions
        SELF:GridViewConditions:Name := "GridViewConditions"
        SELF:GridViewConditions:OptionsCustomization:AllowFilter := false
        SELF:GridViewConditions:OptionsCustomization:AllowGroup := false
        SELF:GridViewConditions:OptionsView:ShowGroupPanel := false
        SELF:GridViewConditions:OptionsView:ShowIndicator := false
        SELF:GridViewConditions:CellValueChanged += DevExpress.XtraGrid.Views.Base.CellValueChangedEventHandler{ SELF, @GridViewConditions_CellValueChanged() }
        SELF:GridViewConditions:CustomUnboundColumnData += DevExpress.XtraGrid.Views.Base.CustomColumnDataEventHandler{ SELF, @GridViewConditions_CustomUnboundColumnData() }
        // 
        // UAlertForm
        // 
        SELF:AutoScaleDimensions := System.Drawing.SizeF{6, 13}
        SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
        SELF:ClientSize := System.Drawing.Size{953, 560}
        SELF:Controls:Add(SELF:splitContainerControl1)
        SELF:Controls:Add(SELF:barDockControlLeft)
        SELF:Controls:Add(SELF:barDockControlRight)
        SELF:Controls:Add(SELF:barDockControlBottom)
        SELF:Controls:Add(SELF:barDockControlTop)
        SELF:Name := "UAlertForm"
        SELF:ShowIcon := false
        SELF:Text := "Alerts"
        SELF:Shown += System.EventHandler{ SELF, @UAlertForm_Shown() }
        ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl1)):EndInit()
        SELF:splitContainerControl1:ResumeLayout(false)
        ((System.ComponentModel.ISupportInitialize)(SELF:GridAlerts)):EndInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:GridViewAlerts)):EndInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:barManager1)):EndInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:barAndDockingController1)):EndInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl2)):EndInit()
        SELF:splitContainerControl2:ResumeLayout(false)
        ((System.ComponentModel.ISupportInitialize)(SELF:TreeListVessels)):EndInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:GridConditions)):EndInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:GridViewConditions)):EndInit()
        SELF:ResumeLayout(false)
        SELF:PerformLayout()
    
        #endregion

END CLASS 
