//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.1.0.0
//     Timestamp      : 20/2/2020 11:05:20
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE FleetManager.Alerts
    PUBLIC PARTIAL CLASS UserAlertsForm ;
        INHERIT System.Windows.Forms.Form
        PRIVATE barManager_Flow AS DevExpress.XtraBars.BarManager
        PRIVATE bar1 AS DevExpress.XtraBars.Bar
        PRIVATE BBINew AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIEdit AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIDelete AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIRefresh AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIPrint AS DevExpress.XtraBars.BarButtonItem
        PRIVATE standaloneBarDockControl_Links AS DevExpress.XtraBars.StandaloneBarDockControl
        PRIVATE BBINew_States AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIEdit_States AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIDelete_States AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIRefresh_States AS DevExpress.XtraBars.BarButtonItem
        PRIVATE BBIPrint_States AS DevExpress.XtraBars.BarButtonItem
        PRIVATE standaloneBarDockControl_Flows AS DevExpress.XtraBars.StandaloneBarDockControl
        PRIVATE barDockControlTop AS DevExpress.XtraBars.BarDockControl
        PRIVATE barDockControlBottom AS DevExpress.XtraBars.BarDockControl
        PRIVATE barDockControlLeft AS DevExpress.XtraBars.BarDockControl
        PRIVATE barDockControlRight AS DevExpress.XtraBars.BarDockControl
        PRIVATE splitContainerControl_Horizontal AS DevExpress.XtraEditors.SplitContainerControl
        PRIVATE splitContainerControl_Vertical AS DevExpress.XtraEditors.SplitContainerControl
        PRIVATE GridLists AS DevExpress.XtraGrid.GridControl
        PRIVATE gridviewlists AS DevExpress.XtraGrid.Views.Grid.GridView
        PRIVATE GridStates AS DevExpress.XtraGrid.GridControl
        PRIVATE gridviewlistitems AS DevExpress.XtraGrid.Views.Grid.GridView
        PRIVATE barAlerts AS DevExpress.XtraBars.Bar
        PRIVATE barConditions AS DevExpress.XtraBars.Bar
        PRIVATE splitContainer1 AS System.Windows.Forms.SplitContainer
        PUBLIC TreeListVessels AS DevExpress.XtraTreeList.TreeList
        PRIVATE gridView1 AS DevExpress.XtraGrid.Views.Grid.GridView
        PRIVATE gridView2 AS DevExpress.XtraGrid.Views.Grid.GridView
        PRIVATE components := NULL AS System.ComponentModel.IContainer
                        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != NULL))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        PRIVATE METHOD InitializeComponent() AS VOID STRICT
            SELF:components := System.ComponentModel.Container{}
            SELF:barManager_Flow := DevExpress.XtraBars.BarManager{SELF:components}
            SELF:bar1 := DevExpress.XtraBars.Bar{}
            SELF:barAlerts := DevExpress.XtraBars.Bar{}
            SELF:BBINew := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIEdit := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIDelete := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIRefresh := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIPrint := DevExpress.XtraBars.BarButtonItem{}
            SELF:standaloneBarDockControl_Links := DevExpress.XtraBars.StandaloneBarDockControl{}
            SELF:barConditions := DevExpress.XtraBars.Bar{}
            SELF:barDockControlTop := DevExpress.XtraBars.BarDockControl{}
            SELF:barDockControlBottom := DevExpress.XtraBars.BarDockControl{}
            SELF:barDockControlLeft := DevExpress.XtraBars.BarDockControl{}
            SELF:barDockControlRight := DevExpress.XtraBars.BarDockControl{}
            SELF:standaloneBarDockControl_Flows := DevExpress.XtraBars.StandaloneBarDockControl{}
            SELF:BBINew_States := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIEdit_States := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIDelete_States := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIRefresh_States := DevExpress.XtraBars.BarButtonItem{}
            SELF:BBIPrint_States := DevExpress.XtraBars.BarButtonItem{}
            SELF:splitContainerControl_Horizontal := DevExpress.XtraEditors.SplitContainerControl{}
            SELF:splitContainerControl_Vertical := DevExpress.XtraEditors.SplitContainerControl{}
            SELF:GridLists := DevExpress.XtraGrid.GridControl{}
            SELF:gridView1 := DevExpress.XtraGrid.Views.Grid.GridView{}
            SELF:gridviewlists := DevExpress.XtraGrid.Views.Grid.GridView{}
            SELF:splitContainer1 := System.Windows.Forms.SplitContainer{}
            SELF:GridStates := DevExpress.XtraGrid.GridControl{}
            SELF:gridView2 := DevExpress.XtraGrid.Views.Grid.GridView{}
            SELF:gridviewlistitems := DevExpress.XtraGrid.Views.Grid.GridView{}
            SELF:TreeListVessels := DevExpress.XtraTreeList.TreeList{}
            ((System.ComponentModel.ISupportInitialize)(SELF:barManager_Flow)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl_Horizontal)):BeginInit()
            SELF:splitContainerControl_Horizontal:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl_Vertical)):BeginInit()
            SELF:splitContainerControl_Vertical:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(SELF:GridLists)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridView1)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridviewlists)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:splitContainer1)):BeginInit()
            SELF:splitContainer1:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(SELF:GridStates)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridView2)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridviewlistitems)):BeginInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:TreeListVessels)):BeginInit()
            SELF:SuspendLayout()
            // 
            // barManager_Flow
            // 
            SELF:barManager_Flow:Bars:AddRange(<DevExpress.XtraBars.Bar>{ SELF:bar1, SELF:barAlerts, SELF:barConditions })
            SELF:barManager_Flow:DockControls:Add(SELF:barDockControlTop)
            SELF:barManager_Flow:DockControls:Add(SELF:barDockControlBottom)
            SELF:barManager_Flow:DockControls:Add(SELF:barDockControlLeft)
            SELF:barManager_Flow:DockControls:Add(SELF:barDockControlRight)
            SELF:barManager_Flow:DockControls:Add(SELF:standaloneBarDockControl_Links)
            SELF:barManager_Flow:DockControls:Add(SELF:standaloneBarDockControl_Flows)
            SELF:barManager_Flow:Form := SELF
            SELF:barManager_Flow:Items:AddRange(<DevExpress.XtraBars.BarItem>{ SELF:BBINew, SELF:BBIEdit, SELF:BBIDelete, SELF:BBIRefresh, SELF:BBIPrint, SELF:BBINew_States, SELF:BBIEdit_States, SELF:BBIDelete_States, SELF:BBIRefresh_States, SELF:BBIPrint_States })
            SELF:barManager_Flow:MainMenu := SELF:barAlerts
            SELF:barManager_Flow:MaxItemId := 22
            SELF:barManager_Flow:StatusBar := SELF:bar1
            // 
            // bar1
            // 
            SELF:bar1:BarName := "Status bar"
            SELF:bar1:DockCol := 0
            SELF:bar1:DockRow := 0
            SELF:bar1:OptionsBar:AllowQuickCustomization := false
            SELF:bar1:OptionsBar:DrawDragBorder := false
            SELF:bar1:OptionsBar:UseWholeRow := true
            SELF:bar1:Text := "Status bar"
            // 
            // barAlerts
            // 
            SELF:barAlerts:BarName := "Main menu"
            SELF:barAlerts:DockCol := 0
            SELF:barAlerts:DockRow := 0
            SELF:barAlerts:FloatLocation := System.Drawing.Point{700, 249}
            SELF:barAlerts:LinksPersistInfo:AddRange(<DevExpress.XtraBars.LinkPersistInfo>{ DevExpress.XtraBars.LinkPersistInfo{SELF:BBINew}, DevExpress.XtraBars.LinkPersistInfo{SELF:BBIEdit}, DevExpress.XtraBars.LinkPersistInfo{SELF:BBIDelete}, DevExpress.XtraBars.LinkPersistInfo{SELF:BBIRefresh}, DevExpress.XtraBars.LinkPersistInfo{SELF:BBIPrint} })
            SELF:barAlerts:OptionsBar:MultiLine := true
            SELF:barAlerts:OptionsBar:UseWholeRow := true
            SELF:barAlerts:Text := "Main menu"
            // 
            // BBINew
            // 
            SELF:BBINew:Caption := "New"
            SELF:BBINew:Id := 0
            SELF:BBINew:Name := "BBINew"
            // 
            // BBIEdit
            // 
            SELF:BBIEdit:Id := 13
            SELF:BBIEdit:Name := "BBIEdit"
            // 
            // BBIDelete
            // 
            SELF:BBIDelete:Id := 14
            SELF:BBIDelete:Name := "BBIDelete"
            // 
            // BBIRefresh
            // 
            SELF:BBIRefresh:Id := 15
            SELF:BBIRefresh:Name := "BBIRefresh"
            // 
            // BBIPrint
            // 
            SELF:BBIPrint:Id := 16
            SELF:BBIPrint:Name := "BBIPrint"
            // 
            // standaloneBarDockControl_Links
            // 
            SELF:standaloneBarDockControl_Links:CausesValidation := false
            SELF:standaloneBarDockControl_Links:Location := System.Drawing.Point{0, 0}
            SELF:standaloneBarDockControl_Links:Manager := SELF:barManager_Flow
            SELF:standaloneBarDockControl_Links:Name := "standaloneBarDockControl_Links"
            SELF:standaloneBarDockControl_Links:Size := System.Drawing.Size{0, 0}
            // 
            // barConditions
            // 
            SELF:barConditions:BarName := "Custom 4"
            SELF:barConditions:DockCol := 0
            SELF:barConditions:DockRow := 0
            SELF:barConditions:FloatLocation := System.Drawing.Point{681, 181}
            SELF:barConditions:Offset := 36
            SELF:barConditions:Text := "Custom 4"
            // 
            // barDockControlTop
            // 
            SELF:barDockControlTop:CausesValidation := false
            SELF:barDockControlTop:Dock := System.Windows.Forms.DockStyle.Top
            SELF:barDockControlTop:Location := System.Drawing.Point{0, 0}
            SELF:barDockControlTop:Manager := SELF:barManager_Flow
            SELF:barDockControlTop:Size := System.Drawing.Size{284, 0}
            // 
            // barDockControlBottom
            // 
            SELF:barDockControlBottom:CausesValidation := false
            SELF:barDockControlBottom:Dock := System.Windows.Forms.DockStyle.Bottom
            SELF:barDockControlBottom:Location := System.Drawing.Point{0, 261}
            SELF:barDockControlBottom:Manager := SELF:barManager_Flow
            SELF:barDockControlBottom:Size := System.Drawing.Size{284, 0}
            // 
            // barDockControlLeft
            // 
            SELF:barDockControlLeft:CausesValidation := false
            SELF:barDockControlLeft:Dock := System.Windows.Forms.DockStyle.Left
            SELF:barDockControlLeft:Location := System.Drawing.Point{0, 0}
            SELF:barDockControlLeft:Manager := SELF:barManager_Flow
            SELF:barDockControlLeft:Size := System.Drawing.Size{0, 261}
            // 
            // barDockControlRight
            // 
            SELF:barDockControlRight:CausesValidation := false
            SELF:barDockControlRight:Dock := System.Windows.Forms.DockStyle.Right
            SELF:barDockControlRight:Location := System.Drawing.Point{284, 0}
            SELF:barDockControlRight:Manager := SELF:barManager_Flow
            SELF:barDockControlRight:Size := System.Drawing.Size{0, 261}
            // 
            // standaloneBarDockControl_Flows
            // 
            SELF:standaloneBarDockControl_Flows:CausesValidation := false
            SELF:standaloneBarDockControl_Flows:Location := System.Drawing.Point{0, 0}
            SELF:standaloneBarDockControl_Flows:Manager := SELF:barManager_Flow
            SELF:standaloneBarDockControl_Flows:Name := "standaloneBarDockControl_Flows"
            SELF:standaloneBarDockControl_Flows:Size := System.Drawing.Size{0, 0}
            // 
            // BBINew_States
            // 
            SELF:BBINew_States:Id := 17
            SELF:BBINew_States:Name := "BBINew_States"
            // 
            // BBIEdit_States
            // 
            SELF:BBIEdit_States:Id := 18
            SELF:BBIEdit_States:Name := "BBIEdit_States"
            // 
            // BBIDelete_States
            // 
            SELF:BBIDelete_States:Id := 19
            SELF:BBIDelete_States:Name := "BBIDelete_States"
            // 
            // BBIRefresh_States
            // 
            SELF:BBIRefresh_States:Id := 20
            SELF:BBIRefresh_States:Name := "BBIRefresh_States"
            // 
            // BBIPrint_States
            // 
            SELF:BBIPrint_States:Id := 21
            SELF:BBIPrint_States:Name := "BBIPrint_States"
            // 
            // splitContainerControl_Horizontal
            // 
            SELF:splitContainerControl_Horizontal:Location := System.Drawing.Point{0, 0}
            SELF:splitContainerControl_Horizontal:Name := "splitContainerControl_Horizontal"
            SELF:splitContainerControl_Horizontal:Size := System.Drawing.Size{200, 100}
            SELF:splitContainerControl_Horizontal:TabIndex := 0
            // 
            // splitContainerControl_Vertical
            // 
            SELF:splitContainerControl_Vertical:Location := System.Drawing.Point{0, 0}
            SELF:splitContainerControl_Vertical:Name := "splitContainerControl_Vertical"
            SELF:splitContainerControl_Vertical:Size := System.Drawing.Size{200, 100}
            SELF:splitContainerControl_Vertical:TabIndex := 0
            // 
            // GridLists
            // 
            SELF:GridLists:Location := System.Drawing.Point{0, 0}
            SELF:GridLists:MainView := SELF:gridView1
            SELF:GridLists:Name := "GridLists"
            SELF:GridLists:Size := System.Drawing.Size{400, 200}
            SELF:GridLists:TabIndex := 0
            SELF:GridLists:ViewCollection:AddRange(<DevExpress.XtraGrid.Views.Base.BaseView>{ SELF:gridView1 })
            // 
            // gridView1
            // 
            SELF:gridView1:GridControl := SELF:GridLists
            SELF:gridView1:Name := "gridView1"
            // 
            // gridviewlists
            // 
            SELF:gridviewlists:Name := "gridviewlists"
            // 
            // splitContainer1
            // 
            SELF:splitContainer1:Location := System.Drawing.Point{0, 0}
            SELF:splitContainer1:Name := "splitContainer1"
            SELF:splitContainer1:Size := System.Drawing.Size{150, 100}
            SELF:splitContainer1:TabIndex := 0
            // 
            // GridStates
            // 
            SELF:GridStates:Location := System.Drawing.Point{0, 0}
            SELF:GridStates:MainView := SELF:gridView2
            SELF:GridStates:Name := "GridStates"
            SELF:GridStates:Size := System.Drawing.Size{400, 200}
            SELF:GridStates:TabIndex := 0
            SELF:GridStates:ViewCollection:AddRange(<DevExpress.XtraGrid.Views.Base.BaseView>{ SELF:gridView2 })
            // 
            // gridView2
            // 
            SELF:gridView2:GridControl := SELF:GridStates
            SELF:gridView2:Name := "gridView2"
            // 
            // gridviewlistitems
            // 
            SELF:gridviewlistitems:Name := "gridviewlistitems"
            // 
            // TreeListVessels
            // 
            SELF:TreeListVessels:Location := System.Drawing.Point{0, 0}
            SELF:TreeListVessels:Name := "TreeListVessels"
            SELF:TreeListVessels:Size := System.Drawing.Size{400, 200}
            SELF:TreeListVessels:TabIndex := 0
            // 
            // UserAlertsForm
            // 
            SELF:ClientSize := System.Drawing.Size{284, 261}
            SELF:Controls:Add(SELF:barDockControlLeft)
            SELF:Controls:Add(SELF:barDockControlRight)
            SELF:Controls:Add(SELF:barDockControlBottom)
            SELF:Controls:Add(SELF:barDockControlTop)
            SELF:Name := "UserAlertsForm"
            ((System.ComponentModel.ISupportInitialize)(SELF:barManager_Flow)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl_Horizontal)):EndInit()
            SELF:splitContainerControl_Horizontal:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(SELF:splitContainerControl_Vertical)):EndInit()
            SELF:splitContainerControl_Vertical:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(SELF:GridLists)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridView1)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridviewlists)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:splitContainer1)):EndInit()
            SELF:splitContainer1:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(SELF:GridStates)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridView2)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:gridviewlistitems)):EndInit()
            ((System.ComponentModel.ISupportInitialize)(SELF:TreeListVessels)):EndInit()
            SELF:ResumeLayout(false)
            SELF:PerformLayout()
    
    END CLASS 
END NAMESPACE
