BEGIN NAMESPACE FleetManager.Properties
    #using System
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")] ;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    INTERNAL CLASS Resources
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        INTERNAL CONSTRUCTOR()
            RETURN
        STATIC PRIVATE resourceMan AS global::System.Resources.ResourceManager
        STATIC PRIVATE resourceCulture AS global::System.Globalization.CultureInfo
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY ResourceManager AS global::System.Resources.ResourceManager
        
            GET
                IF System.Object.ReferenceEquals(resourceMan, NULL)
                    LOCAL temp := global::System.Resources.ResourceManager{"FleetManager.Properties.Resources", typeof(Resources):Assembly} AS global::System.Resources.ResourceManager
                    resourceMan := temp
                ENDIF
                RETURN resourceMan
            END GET
        END PROPERTY
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY Culture AS global::System.Globalization.CultureInfo
        
            GET
                RETURN resourceCulture
            END GET
        
            SET
                resourceCulture := value
            END SET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        INTERNAL STATIC PROPERTY xls AS System.Drawing.Bitmap
        
            GET
                LOCAL obj := ResourceManager:GetObject("xls", resourceCulture) AS System.Object
                RETURN ((System.Drawing.Bitmap)(obj))
            END GET
        END PROPERTY
    
    END CLASS
END NAMESPACE
