//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.1.0.0
//     Timestamp      : 21/2/2020 15:12:24
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
PUBLIC PARTIAL CLASS FSHelpForm ;
    INHERIT System.Windows.Forms.Form
    PRIVATE dataGridView1 AS System.Windows.Forms.DataGridView
    PRIVATE components := NULL AS System.ComponentModel.IContainer
                                                                                
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
    PRIVATE METHOD InitializeComponent() AS VOID STRICT
        LOCAL dataGridViewCellStyle1 := System.Windows.Forms.DataGridViewCellStyle{} AS System.Windows.Forms.DataGridViewCellStyle
        SELF:dataGridView1 := System.Windows.Forms.DataGridView{}
        ((System.ComponentModel.ISupportInitialize)(SELF:dataGridView1)):BeginInit()
        SELF:SuspendLayout()
        // 
        // dataGridView1
        // 
        SELF:dataGridView1:AllowUserToAddRows := false
        SELF:dataGridView1:AllowUserToDeleteRows := false
        SELF:dataGridView1:AutoSizeColumnsMode := System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill
        SELF:dataGridView1:BackgroundColor := System.Drawing.SystemColors.Control
        SELF:dataGridView1:BorderStyle := System.Windows.Forms.BorderStyle.None
        SELF:dataGridView1:ColumnHeadersHeightSizeMode := System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        dataGridViewCellStyle1:Alignment := System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
        dataGridViewCellStyle1:BackColor := System.Drawing.SystemColors.Control
        dataGridViewCellStyle1:Font := System.Drawing.Font{"Tahoma", 9, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(161))}
        dataGridViewCellStyle1:ForeColor := System.Drawing.SystemColors.ControlText
        dataGridViewCellStyle1:SelectionBackColor := System.Drawing.SystemColors.Highlight
        dataGridViewCellStyle1:SelectionForeColor := System.Drawing.SystemColors.HighlightText
        dataGridViewCellStyle1:WrapMode := System.Windows.Forms.DataGridViewTriState.False
        SELF:dataGridView1:DefaultCellStyle := dataGridViewCellStyle1
        SELF:dataGridView1:Dock := System.Windows.Forms.DockStyle.Fill
        SELF:dataGridView1:Location := System.Drawing.Point{0, 0}
        SELF:dataGridView1:Name := "dataGridView1"
        SELF:dataGridView1:ReadOnly := true
        SELF:dataGridView1:RowHeadersVisible := false
        SELF:dataGridView1:ShowCellToolTips := false
        SELF:dataGridView1:ShowEditingIcon := false
        SELF:dataGridView1:Size := System.Drawing.Size{509, 261}
        SELF:dataGridView1:TabIndex := 0
        // 
        // FSHelpForm
        // 
        SELF:AutoScaleDimensions := System.Drawing.SizeF{6, 13}
        SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
        SELF:ClientSize := System.Drawing.Size{509, 261}
        SELF:Controls:Add(SELF:dataGridView1)
        SELF:FormBorderStyle := System.Windows.Forms.FormBorderStyle.FixedToolWindow
        SELF:MaximizeBox := false
        SELF:MinimizeBox := false
        SELF:Name := "FSHelpForm"
        SELF:StartPosition := System.Windows.Forms.FormStartPosition.CenterParent
        SELF:Text := "FS Help Form"
        SELF:FormClosing += System.Windows.Forms.FormClosingEventHandler{ SELF, @FSHelpForm_FormClosing() }
        SELF:Load += System.EventHandler{ SELF, @FSHelpForm_Load() }
        SELF:Shown += System.EventHandler{ SELF, @FSHelpForm_Shown() }
        ((System.ComponentModel.ISupportInitialize)(SELF:dataGridView1)):EndInit()
        SELF:ResumeLayout(false)
    
        #endregion

END CLASS 
