//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.1.0.0
//     Timestamp      : 20/2/2020 11:28:17
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
PUBLIC PARTIAL CLASS NewVoyageForm ;
    INHERIT System.Windows.Forms.Form
    PRIVATE components := NULL AS System.ComponentModel.IContainer
    PRIVATE barManager1 AS DevExpress.XtraBars.BarManager
    PRIVATE bar2 AS DevExpress.XtraBars.Bar
    PRIVATE barDockControlTop AS DevExpress.XtraBars.BarDockControl
    PRIVATE barDockControlBottom AS DevExpress.XtraBars.BarDockControl
    PRIVATE barDockControlLeft AS DevExpress.XtraBars.BarDockControl
    PRIVATE RefreshFormBtn AS DevExpress.XtraBars.BarButtonItem
    PRIVATE CloseFormBtn AS DevExpress.XtraBars.BarButtonItem
    PRIVATE SaveBtn AS DevExpress.XtraBars.BarButtonItem
    PRIVATE panel1 AS System.Windows.Forms.Panel
    PRIVATE FromGC AS DevExpress.XtraEditors.GroupControl
    PRIVATE label3 AS System.Windows.Forms.Label
    PRIVATE label2 AS System.Windows.Forms.Label
    PRIVATE label1 AS System.Windows.Forms.Label
    PRIVATE ToGC AS DevExpress.XtraEditors.GroupControl
    PRIVATE label7 AS System.Windows.Forms.Label
    PRIVATE label8 AS System.Windows.Forms.Label
    PRIVATE label9 AS System.Windows.Forms.Label
    PRIVATE label10 AS System.Windows.Forms.Label
    PRIVATE label6 AS System.Windows.Forms.Label
    PRIVATE label5 AS System.Windows.Forms.Label
    PRIVATE label4 AS System.Windows.Forms.Label
    PRIVATE VesselNameLbl AS System.Windows.Forms.Label
    PRIVATE descriptionTb AS System.Windows.Forms.TextBox
    PRIVATE startDate AS System.Windows.Forms.DateTimePicker
    PRIVATE endDate AS System.Windows.Forms.DateTimePicker
    PRIVATE typeCb AS System.Windows.Forms.ComboBox
    PRIVATE toPortCb AS System.Windows.Forms.ComboBox
    PRIVATE endGmtDate AS System.Windows.Forms.DateTimePicker
    PRIVATE toGmtTb AS System.Windows.Forms.TextBox
    PRIVATE fromPortCb AS System.Windows.Forms.ComboBox
    PRIVATE startGmtDate AS System.Windows.Forms.DateTimePicker
    PRIVATE fromGmtTb AS System.Windows.Forms.TextBox
    PRIVATE label11 AS System.Windows.Forms.Label
    PRIVATE chartererTb AS System.Windows.Forms.TextBox
    PRIVATE AddPortToBtn AS System.Windows.Forms.Button
    PRIVATE PortDestinationDG AS System.Windows.Forms.DataGridView
    PRIVATE voyageNoTb AS System.Windows.Forms.TextBox
    PRIVATE label12 AS System.Windows.Forms.Label
    PRIVATE bbiCreateFolders AS DevExpress.XtraBars.BarButtonItem
    PRIVATE barAndDockingController1 AS DevExpress.XtraBars.BarAndDockingController
    PRIVATE barDockControlRight AS DevExpress.XtraBars.BarDockControl
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
    PRIVATE METHOD InitializeComponent() AS VOID STRICT
        SELF:components := System.ComponentModel.Container{}
        LOCAL superToolTip18 := DevExpress.Utils.SuperToolTip{} AS DevExpress.Utils.SuperToolTip
        LOCAL toolTipTitleItem18 := DevExpress.Utils.ToolTipTitleItem{} AS DevExpress.Utils.ToolTipTitleItem
        LOCAL toolTipItem12 := DevExpress.Utils.ToolTipItem{} AS DevExpress.Utils.ToolTipItem
        LOCAL resources := System.ComponentModel.ComponentResourceManager{TYPEOF(NewVoyageForm)} AS System.ComponentModel.ComponentResourceManager
        LOCAL superToolTip16 := DevExpress.Utils.SuperToolTip{} AS DevExpress.Utils.SuperToolTip
        LOCAL toolTipTitleItem16 := DevExpress.Utils.ToolTipTitleItem{} AS DevExpress.Utils.ToolTipTitleItem
        LOCAL superToolTip17 := DevExpress.Utils.SuperToolTip{} AS DevExpress.Utils.SuperToolTip
        LOCAL toolTipTitleItem17 := DevExpress.Utils.ToolTipTitleItem{} AS DevExpress.Utils.ToolTipTitleItem
        LOCAL toolTipItem11 := DevExpress.Utils.ToolTipItem{} AS DevExpress.Utils.ToolTipItem
        SELF:barManager1 := DevExpress.XtraBars.BarManager{SELF:components}
        SELF:bar2 := DevExpress.XtraBars.Bar{}
        SELF:SaveBtn := DevExpress.XtraBars.BarButtonItem{}
        SELF:RefreshFormBtn := DevExpress.XtraBars.BarButtonItem{}
        SELF:bbiCreateFolders := DevExpress.XtraBars.BarButtonItem{}
        SELF:CloseFormBtn := DevExpress.XtraBars.BarButtonItem{}
        SELF:barDockControlTop := DevExpress.XtraBars.BarDockControl{}
        SELF:barDockControlBottom := DevExpress.XtraBars.BarDockControl{}
        SELF:barDockControlLeft := DevExpress.XtraBars.BarDockControl{}
        SELF:barDockControlRight := DevExpress.XtraBars.BarDockControl{}
        SELF:VesselNameLbl := System.Windows.Forms.Label{}
        SELF:panel1 := System.Windows.Forms.Panel{}
        SELF:voyageNoTb := System.Windows.Forms.TextBox{}
        SELF:label12 := System.Windows.Forms.Label{}
        SELF:chartererTb := System.Windows.Forms.TextBox{}
        SELF:label11 := System.Windows.Forms.Label{}
        SELF:typeCb := System.Windows.Forms.ComboBox{}
        SELF:ToGC := DevExpress.XtraEditors.GroupControl{}
        SELF:AddPortToBtn := System.Windows.Forms.Button{}
        SELF:PortDestinationDG := System.Windows.Forms.DataGridView{}
        SELF:toPortCb := System.Windows.Forms.ComboBox{}
        SELF:endGmtDate := System.Windows.Forms.DateTimePicker{}
        SELF:endDate := System.Windows.Forms.DateTimePicker{}
        SELF:label7 := System.Windows.Forms.Label{}
        SELF:label8 := System.Windows.Forms.Label{}
        SELF:toGmtTb := System.Windows.Forms.TextBox{}
        SELF:label9 := System.Windows.Forms.Label{}
        SELF:label10 := System.Windows.Forms.Label{}
        SELF:FromGC := DevExpress.XtraEditors.GroupControl{}
        SELF:fromPortCb := System.Windows.Forms.ComboBox{}
        SELF:startGmtDate := System.Windows.Forms.DateTimePicker{}
        SELF:startDate := System.Windows.Forms.DateTimePicker{}
        SELF:label6 := System.Windows.Forms.Label{}
        SELF:label5 := System.Windows.Forms.Label{}
        SELF:fromGmtTb := System.Windows.Forms.TextBox{}
        SELF:label4 := System.Windows.Forms.Label{}
        SELF:label3 := System.Windows.Forms.Label{}
        SELF:label2 := System.Windows.Forms.Label{}
        SELF:descriptionTb := System.Windows.Forms.TextBox{}
        SELF:label1 := System.Windows.Forms.Label{}
        SELF:barAndDockingController1 := DevExpress.XtraBars.BarAndDockingController{SELF:components}
        ((System.ComponentModel.ISupportInitialize)(SELF:barManager1)):BeginInit()
        SELF:panel1:SuspendLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:ToGC)):BeginInit()
        SELF:ToGC:SuspendLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:PortDestinationDG)):BeginInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:FromGC)):BeginInit()
        SELF:FromGC:SuspendLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:barAndDockingController1)):BeginInit()
        SELF:SuspendLayout()
        // 
        // barManager1
        // 
        SELF:barManager1:Bars:AddRange(<DevExpress.XtraBars.Bar>{ SELF:bar2 })
        SELF:barManager1:Controller := SELF:barAndDockingController1
        SELF:barManager1:DockControls:Add(SELF:barDockControlTop)
        SELF:barManager1:DockControls:Add(SELF:barDockControlBottom)
        SELF:barManager1:DockControls:Add(SELF:barDockControlLeft)
        SELF:barManager1:DockControls:Add(SELF:barDockControlRight)
        SELF:barManager1:Form := SELF
        SELF:barManager1:Items:AddRange(<DevExpress.XtraBars.BarItem>{ SELF:RefreshFormBtn, SELF:CloseFormBtn, SELF:SaveBtn, SELF:bbiCreateFolders })
        SELF:barManager1:MainMenu := SELF:bar2
        SELF:barManager1:MaxItemId := 4
        // 
        // bar2
        // 
        SELF:bar2:BarName := "Main menu"
        SELF:bar2:DockCol := 0
        SELF:bar2:DockRow := 0
        SELF:bar2:DockStyle := DevExpress.XtraBars.BarDockStyle.Top
        SELF:bar2:LinksPersistInfo:AddRange(<DevExpress.XtraBars.LinkPersistInfo>{ DevExpress.XtraBars.LinkPersistInfo{SELF:SaveBtn}, DevExpress.XtraBars.LinkPersistInfo{SELF:RefreshFormBtn}, DevExpress.XtraBars.LinkPersistInfo{SELF:bbiCreateFolders}, DevExpress.XtraBars.LinkPersistInfo{SELF:CloseFormBtn} })
        SELF:bar2:OptionsBar:AllowQuickCustomization := false
        SELF:bar2:OptionsBar:AutoPopupMode := DevExpress.XtraBars.BarAutoPopupMode.None
        SELF:bar2:OptionsBar:MultiLine := true
        SELF:bar2:OptionsBar:UseWholeRow := true
        SELF:bar2:Text := "Main menu"
        // 
        // SaveBtn
        // 
        SELF:SaveBtn:Caption := "Save"
        SELF:SaveBtn:Id := 2
        SELF:SaveBtn:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("SaveBtn.ImageOptions.Image")))
        SELF:SaveBtn:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("SaveBtn.ImageOptions.LargeImage")))
        SELF:SaveBtn:ItemShortcut := DevExpress.XtraBars.BarShortcut{(System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)}
        SELF:SaveBtn:Name := "SaveBtn"
        toolTipTitleItem18:Text := "Save(Ctrl+S)"
        toolTipItem12:LeftIndent := 6
        toolTipItem12:Text := "Save Voyage"
        superToolTip18:Items:Add(toolTipTitleItem18)
        superToolTip18:Items:Add(toolTipItem12)
        SELF:SaveBtn:SuperTip := superToolTip18
        SELF:SaveBtn:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @SaveBtn_ItemClick() }
        // 
        // RefreshFormBtn
        // 
        SELF:RefreshFormBtn:Caption := "Refresh"
        SELF:RefreshFormBtn:Id := 0
        SELF:RefreshFormBtn:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("RefreshFormBtn.ImageOptions.Image")))
        SELF:RefreshFormBtn:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("RefreshFormBtn.ImageOptions.LargeImage")))
        SELF:RefreshFormBtn:Name := "RefreshFormBtn"
        toolTipTitleItem16:Text := "Refresh"
        superToolTip16:Items:Add(toolTipTitleItem16)
        SELF:RefreshFormBtn:SuperTip := superToolTip16
        SELF:RefreshFormBtn:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @RefreshFormBtn_ItemClick() }
        // 
        // bbiCreateFolders
        // 
        SELF:bbiCreateFolders:Caption := "Create Folder Structure"
        SELF:bbiCreateFolders:Id := 3
        SELF:bbiCreateFolders:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("bbiCreateFolders.ImageOptions.Image")))
        SELF:bbiCreateFolders:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("bbiCreateFolders.ImageOptions.LargeImage")))
        SELF:bbiCreateFolders:Name := "bbiCreateFolders"
        SELF:bbiCreateFolders:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @bbiCreateFolders_ItemClick() }
        // 
        // CloseFormBtn
        // 
        SELF:CloseFormBtn:Caption := "Close Form"
        SELF:CloseFormBtn:Id := 1
        SELF:CloseFormBtn:ImageOptions:Image := ((System.Drawing.Image)(resources:GetObject("CloseFormBtn.ImageOptions.Image")))
        SELF:CloseFormBtn:ImageOptions:LargeImage := ((System.Drawing.Image)(resources:GetObject("CloseFormBtn.ImageOptions.LargeImage")))
        SELF:CloseFormBtn:ItemShortcut := DevExpress.XtraBars.BarShortcut{(System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.F4)}
        SELF:CloseFormBtn:Name := "CloseFormBtn"
        toolTipTitleItem17:Text := "Alt+F4"
        toolTipItem11:LeftIndent := 6
        toolTipItem11:Text := "Close Form"
        superToolTip17:Items:Add(toolTipTitleItem17)
        superToolTip17:Items:Add(toolTipItem11)
        SELF:CloseFormBtn:SuperTip := superToolTip17
        SELF:CloseFormBtn:ItemClick += DevExpress.XtraBars.ItemClickEventHandler{ SELF, @CloseFormBtn_ItemClick() }
        // 
        // barDockControlTop
        // 
        SELF:barDockControlTop:CausesValidation := false
        SELF:barDockControlTop:Dock := System.Windows.Forms.DockStyle.Top
        SELF:barDockControlTop:Location := System.Drawing.Point{0, 0}
        SELF:barDockControlTop:Manager := SELF:barManager1
        SELF:barDockControlTop:Size := System.Drawing.Size{391, 24}
        // 
        // barDockControlBottom
        // 
        SELF:barDockControlBottom:CausesValidation := false
        SELF:barDockControlBottom:Dock := System.Windows.Forms.DockStyle.Bottom
        SELF:barDockControlBottom:Location := System.Drawing.Point{0, 619}
        SELF:barDockControlBottom:Manager := SELF:barManager1
        SELF:barDockControlBottom:Size := System.Drawing.Size{391, 0}
        // 
        // barDockControlLeft
        // 
        SELF:barDockControlLeft:CausesValidation := false
        SELF:barDockControlLeft:Dock := System.Windows.Forms.DockStyle.Left
        SELF:barDockControlLeft:Location := System.Drawing.Point{0, 24}
        SELF:barDockControlLeft:Manager := SELF:barManager1
        SELF:barDockControlLeft:Size := System.Drawing.Size{0, 595}
        // 
        // barDockControlRight
        // 
        SELF:barDockControlRight:CausesValidation := false
        SELF:barDockControlRight:Dock := System.Windows.Forms.DockStyle.Right
        SELF:barDockControlRight:Location := System.Drawing.Point{391, 24}
        SELF:barDockControlRight:Manager := SELF:barManager1
        SELF:barDockControlRight:Size := System.Drawing.Size{0, 595}
        // 
        // VesselNameLbl
        // 
        SELF:VesselNameLbl:AutoSize := true
        SELF:VesselNameLbl:Font := System.Drawing.Font{"Tahoma", 9.25, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((BYTE)(161))}
        SELF:VesselNameLbl:Location := System.Drawing.Point{15, 41}
        SELF:VesselNameLbl:Name := "VesselNameLbl"
        SELF:VesselNameLbl:Size := System.Drawing.Size{101, 16}
        SELF:VesselNameLbl:TabIndex := 4
        SELF:VesselNameLbl:Text := "[Vessel Name]"
        // 
        // panel1
        // 
        SELF:panel1:Controls:Add(SELF:voyageNoTb)
        SELF:panel1:Controls:Add(SELF:label12)
        SELF:panel1:Controls:Add(SELF:chartererTb)
        SELF:panel1:Controls:Add(SELF:label11)
        SELF:panel1:Controls:Add(SELF:typeCb)
        SELF:panel1:Controls:Add(SELF:ToGC)
        SELF:panel1:Controls:Add(SELF:FromGC)
        SELF:panel1:Controls:Add(SELF:label2)
        SELF:panel1:Controls:Add(SELF:descriptionTb)
        SELF:panel1:Controls:Add(SELF:label1)
        SELF:panel1:Location := System.Drawing.Point{15, 60}
        SELF:panel1:Name := "panel1"
        SELF:panel1:Size := System.Drawing.Size{360, 541}
        SELF:panel1:TabIndex := 9
        // 
        // voyageNoTb
        // 
        SELF:voyageNoTb:Font := System.Drawing.Font{"Tahoma", 9.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(161))}
        SELF:voyageNoTb:Location := System.Drawing.Point{114, 39}
        SELF:voyageNoTb:Name := "voyageNoTb"
        SELF:voyageNoTb:Size := System.Drawing.Size{214, 22}
        SELF:voyageNoTb:TabIndex := 3
        SELF:voyageNoTb:KeyPress += System.Windows.Forms.KeyPressEventHandler{ SELF, @voyageNoTb_KeyPress() }
        // 
        // label12
        // 
        SELF:label12:AutoSize := true
        SELF:label12:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label12:Location := System.Drawing.Point{40, 41}
        SELF:label12:Name := "label12"
        SELF:label12:Size := System.Drawing.Size{69, 16}
        SELF:label12:TabIndex := 2
        SELF:label12:Text := "Voyage No"
        SELF:label12:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // chartererTb
        // 
        SELF:chartererTb:Font := System.Drawing.Font{"Tahoma", 9.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(161))}
        SELF:chartererTb:Location := System.Drawing.Point{114, 93}
        SELF:chartererTb:Name := "chartererTb"
        SELF:chartererTb:Size := System.Drawing.Size{214, 22}
        SELF:chartererTb:TabIndex := 7
        SELF:chartererTb:Click += System.EventHandler{ SELF, @chartererTb_Click() }
        SELF:chartererTb:KeyDown += System.Windows.Forms.KeyEventHandler{ SELF, @chartererTb_KeyDown() }
        // 
        // label11
        // 
        SELF:label11:AutoSize := true
        SELF:label11:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label11:Location := System.Drawing.Point{45, 95}
        SELF:label11:Name := "label11"
        SELF:label11:Size := System.Drawing.Size{63, 16}
        SELF:label11:TabIndex := 6
        SELF:label11:Text := "Charterer"
        SELF:label11:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // typeCb
        // 
        SELF:typeCb:AutoCompleteMode := System.Windows.Forms.AutoCompleteMode.Append
        SELF:typeCb:AutoCompleteSource := System.Windows.Forms.AutoCompleteSource.ListItems
        SELF:typeCb:FormattingEnabled := true
        SELF:typeCb:Location := System.Drawing.Point{114, 67}
        SELF:typeCb:Name := "typeCb"
        SELF:typeCb:Size := System.Drawing.Size{214, 21}
        SELF:typeCb:TabIndex := 5
        SELF:typeCb:Leave += System.EventHandler{ SELF, @typeCb_Leave() }
        // 
        // ToGC
        // 
        SELF:ToGC:Controls:Add(SELF:AddPortToBtn)
        SELF:ToGC:Controls:Add(SELF:PortDestinationDG)
        SELF:ToGC:Controls:Add(SELF:toPortCb)
        SELF:ToGC:Controls:Add(SELF:endGmtDate)
        SELF:ToGC:Controls:Add(SELF:endDate)
        SELF:ToGC:Controls:Add(SELF:label7)
        SELF:ToGC:Controls:Add(SELF:label8)
        SELF:ToGC:Controls:Add(SELF:toGmtTb)
        SELF:ToGC:Controls:Add(SELF:label9)
        SELF:ToGC:Controls:Add(SELF:label10)
        SELF:ToGC:Location := System.Drawing.Point{4, 272}
        SELF:ToGC:Name := "ToGC"
        SELF:ToGC:Size := System.Drawing.Size{353, 263}
        SELF:ToGC:TabIndex := 12
        SELF:ToGC:Text := "To"
        // 
        // AddPortToBtn
        // 
        SELF:AddPortToBtn:Location := System.Drawing.Point{300, 25}
        SELF:AddPortToBtn:Name := "AddPortToBtn"
        SELF:AddPortToBtn:Size := System.Drawing.Size{25, 23}
        SELF:AddPortToBtn:TabIndex := 3
        SELF:AddPortToBtn:Text := "+"
        SELF:AddPortToBtn:UseVisualStyleBackColor := true
        SELF:AddPortToBtn:Click += System.EventHandler{ SELF, @AddPortToBtn_Click() }
        // 
        // PortDestinationDG
        // 
        SELF:PortDestinationDG:AllowUserToAddRows := false
        SELF:PortDestinationDG:AutoSizeColumnsMode := System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill
        SELF:PortDestinationDG:BackgroundColor := System.Drawing.SystemColors.Control
        SELF:PortDestinationDG:BorderStyle := System.Windows.Forms.BorderStyle.Fixed3D
        SELF:PortDestinationDG:CellBorderStyle := System.Windows.Forms.DataGridViewCellBorderStyle.Raised
        SELF:PortDestinationDG:ColumnHeadersHeightSizeMode := System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        SELF:PortDestinationDG:GridColor := System.Drawing.SystemColors.Control
        SELF:PortDestinationDG:Location := System.Drawing.Point{111, 53}
        SELF:PortDestinationDG:Name := "PortDestinationDG"
        SELF:PortDestinationDG:ReadOnly := true
        SELF:PortDestinationDG:Size := System.Drawing.Size{214, 115}
        SELF:PortDestinationDG:TabIndex := 12
        // 
        // toPortCb
        // 
        SELF:toPortCb:AutoCompleteMode := System.Windows.Forms.AutoCompleteMode.SuggestAppend
        SELF:toPortCb:AutoCompleteSource := System.Windows.Forms.AutoCompleteSource.ListItems
        SELF:toPortCb:FormattingEnabled := true
        SELF:toPortCb:Location := System.Drawing.Point{111, 26}
        SELF:toPortCb:Name := "toPortCb"
        SELF:toPortCb:Size := System.Drawing.Size{183, 21}
        SELF:toPortCb:TabIndex := 2
        SELF:toPortCb:Leave += System.EventHandler{ SELF, @toPortCb_Leave() }
        // 
        // endGmtDate
        // 
        SELF:endGmtDate:CalendarFont := System.Drawing.Font{"Tahoma", 9.25}
        SELF:endGmtDate:CustomFormat := "dd/MM/yyyy HH:mm:ss"
        SELF:endGmtDate:Enabled := false
        SELF:endGmtDate:Format := System.Windows.Forms.DateTimePickerFormat.Custom
        SELF:endGmtDate:Location := System.Drawing.Point{111, 229}
        SELF:endGmtDate:Name := "endGmtDate"
        SELF:endGmtDate:Size := System.Drawing.Size{214, 21}
        SELF:endGmtDate:TabIndex := 9
        // 
        // endDate
        // 
        SELF:endDate:CalendarFont := System.Drawing.Font{"Tahoma", 9.25}
        SELF:endDate:CustomFormat := "dd/MM/yyyy HH:mm:ss"
        SELF:endDate:Format := System.Windows.Forms.DateTimePickerFormat.Custom
        SELF:endDate:Location := System.Drawing.Point{111, 202}
        SELF:endDate:Name := "endDate"
        SELF:endDate:Size := System.Drawing.Size{214, 21}
        SELF:endDate:TabIndex := 7
        SELF:endDate:ValueChanged += System.EventHandler{ SELF, @endDate_ValueChanged() }
        // 
        // label7
        // 
        SELF:label7:AutoSize := true
        SELF:label7:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label7:Location := System.Drawing.Point{16, 232}
        SELF:label7:Name := "label7"
        SELF:label7:Size := System.Drawing.Size{89, 16}
        SELF:label7:TabIndex := 8
        SELF:label7:Text := "End Date GMT"
        SELF:label7:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // label8
        // 
        SELF:label8:AutoSize := true
        SELF:label8:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label8:Location := System.Drawing.Point{46, 206}
        SELF:label8:Name := "label8"
        SELF:label8:Size := System.Drawing.Size{59, 16}
        SELF:label8:TabIndex := 6
        SELF:label8:Text := "End Date"
        SELF:label8:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // toGmtTb
        // 
        SELF:toGmtTb:Enabled := false
        SELF:toGmtTb:Font := System.Drawing.Font{"Tahoma", 9.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(161))}
        SELF:toGmtTb:Location := System.Drawing.Point{111, 174}
        SELF:toGmtTb:Name := "toGmtTb"
        SELF:toGmtTb:Size := System.Drawing.Size{39, 22}
        SELF:toGmtTb:TabIndex := 5
        // 
        // label9
        // 
        SELF:label9:AutoSize := true
        SELF:label9:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label9:Location := System.Drawing.Point{53, 176}
        SELF:label9:Name := "label9"
        SELF:label9:Size := System.Drawing.Size{52, 16}
        SELF:label9:TabIndex := 4
        SELF:label9:Text := "+/-GMT"
        SELF:label9:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // label10
        // 
        SELF:label10:AutoSize := true
        SELF:label10:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label10:Location := System.Drawing.Point{74, 27}
        SELF:label10:Name := "label10"
        SELF:label10:Size := System.Drawing.Size{31, 16}
        SELF:label10:TabIndex := 1
        SELF:label10:Text := "Port"
        SELF:label10:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // FromGC
        // 
        SELF:FromGC:Controls:Add(SELF:fromPortCb)
        SELF:FromGC:Controls:Add(SELF:startGmtDate)
        SELF:FromGC:Controls:Add(SELF:startDate)
        SELF:FromGC:Controls:Add(SELF:label6)
        SELF:FromGC:Controls:Add(SELF:label5)
        SELF:FromGC:Controls:Add(SELF:fromGmtTb)
        SELF:FromGC:Controls:Add(SELF:label4)
        SELF:FromGC:Controls:Add(SELF:label3)
        SELF:FromGC:Location := System.Drawing.Point{4, 121}
        SELF:FromGC:Name := "FromGC"
        SELF:FromGC:Size := System.Drawing.Size{353, 145}
        SELF:FromGC:TabIndex := 8
        SELF:FromGC:Text := "From"
        SELF:FromGC:Paint += System.Windows.Forms.PaintEventHandler{ SELF, @FromGC_Paint() }
        // 
        // fromPortCb
        // 
        SELF:fromPortCb:AutoCompleteMode := System.Windows.Forms.AutoCompleteMode.SuggestAppend
        SELF:fromPortCb:AutoCompleteSource := System.Windows.Forms.AutoCompleteSource.ListItems
        SELF:fromPortCb:FormattingEnabled := true
        SELF:fromPortCb:Location := System.Drawing.Point{111, 26}
        SELF:fromPortCb:Name := "fromPortCb"
        SELF:fromPortCb:Size := System.Drawing.Size{214, 21}
        SELF:fromPortCb:TabIndex := 2
        SELF:fromPortCb:SelectedValueChanged += System.EventHandler{ SELF, @fromPortCb_SelectedValueChanged() }
        SELF:fromPortCb:Leave += System.EventHandler{ SELF, @fromPortCb_Leave() }
        // 
        // startGmtDate
        // 
        SELF:startGmtDate:CalendarFont := System.Drawing.Font{"Tahoma", 9.25}
        SELF:startGmtDate:CustomFormat := "dd/MM/yyyy HH:mm:ss"
        SELF:startGmtDate:Enabled := false
        SELF:startGmtDate:Format := System.Windows.Forms.DateTimePickerFormat.Custom
        SELF:startGmtDate:Location := System.Drawing.Point{111, 108}
        SELF:startGmtDate:Name := "startGmtDate"
        SELF:startGmtDate:Size := System.Drawing.Size{214, 21}
        SELF:startGmtDate:TabIndex := 8
        // 
        // startDate
        // 
        SELF:startDate:CalendarFont := System.Drawing.Font{"Tahoma", 9.25}
        SELF:startDate:CustomFormat := "dd/MM/yyyy HH:mm:ss"
        SELF:startDate:Format := System.Windows.Forms.DateTimePickerFormat.Custom
        SELF:startDate:Location := System.Drawing.Point{111, 81}
        SELF:startDate:Name := "startDate"
        SELF:startDate:Size := System.Drawing.Size{214, 21}
        SELF:startDate:TabIndex := 6
        SELF:startDate:ValueChanged += System.EventHandler{ SELF, @startDate_ValueChanged() }
        // 
        // label6
        // 
        SELF:label6:AutoSize := true
        SELF:label6:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label6:Location := System.Drawing.Point{12, 111}
        SELF:label6:Name := "label6"
        SELF:label6:Size := System.Drawing.Size{96, 16}
        SELF:label6:TabIndex := 7
        SELF:label6:Text := "Start Date GMT"
        SELF:label6:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // label5
        // 
        SELF:label5:AutoSize := true
        SELF:label5:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label5:Location := System.Drawing.Point{39, 85}
        SELF:label5:Name := "label5"
        SELF:label5:Size := System.Drawing.Size{66, 16}
        SELF:label5:TabIndex := 5
        SELF:label5:Text := "Start Date"
        SELF:label5:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // fromGmtTb
        // 
        SELF:fromGmtTb:Enabled := false
        SELF:fromGmtTb:Font := System.Drawing.Font{"Tahoma", 9.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(161))}
        SELF:fromGmtTb:Location := System.Drawing.Point{111, 53}
        SELF:fromGmtTb:Name := "fromGmtTb"
        SELF:fromGmtTb:Size := System.Drawing.Size{39, 22}
        SELF:fromGmtTb:TabIndex := 4
        // 
        // label4
        // 
        SELF:label4:AutoSize := true
        SELF:label4:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label4:Location := System.Drawing.Point{53, 55}
        SELF:label4:Name := "label4"
        SELF:label4:Size := System.Drawing.Size{52, 16}
        SELF:label4:TabIndex := 3
        SELF:label4:Text := "+/-GMT"
        SELF:label4:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // label3
        // 
        SELF:label3:AutoSize := true
        SELF:label3:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label3:Location := System.Drawing.Point{74, 27}
        SELF:label3:Name := "label3"
        SELF:label3:Size := System.Drawing.Size{31, 16}
        SELF:label3:TabIndex := 1
        SELF:label3:Text := "Port"
        SELF:label3:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // label2
        // 
        SELF:label2:AutoSize := true
        SELF:label2:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label2:Location := System.Drawing.Point{72, 69}
        SELF:label2:Name := "label2"
        SELF:label2:Size := System.Drawing.Size{36, 16}
        SELF:label2:TabIndex := 4
        SELF:label2:Text := "Type"
        SELF:label2:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // descriptionTb
        // 
        SELF:descriptionTb:Font := System.Drawing.Font{"Tahoma", 9.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(161))}
        SELF:descriptionTb:Location := System.Drawing.Point{114, 11}
        SELF:descriptionTb:Name := "descriptionTb"
        SELF:descriptionTb:Size := System.Drawing.Size{214, 22}
        SELF:descriptionTb:TabIndex := 1
        SELF:descriptionTb:TextChanged += System.EventHandler{ SELF, @descriptionTb_TextChanged() }
        // 
        // label1
        // 
        SELF:label1:AutoSize := true
        SELF:label1:Font := System.Drawing.Font{"Tahoma", 9.25}
        SELF:label1:Location := System.Drawing.Point{37, 14}
        SELF:label1:Name := "label1"
        SELF:label1:Size := System.Drawing.Size{71, 16}
        SELF:label1:TabIndex := 0
        SELF:label1:Text := "Description"
        SELF:label1:TextAlign := System.Drawing.ContentAlignment.MiddleRight
        // 
        // barAndDockingController1
        // 
        SELF:barAndDockingController1:PropertiesBar:AllowLinkLighting := false
        SELF:barAndDockingController1:PropertiesBar:DefaultGlyphSize := System.Drawing.Size{16, 16}
        SELF:barAndDockingController1:PropertiesBar:DefaultLargeGlyphSize := System.Drawing.Size{32, 32}
        // 
        // NewVoyageForm
        // 
        SELF:AutoScaleDimensions := System.Drawing.SizeF{6, 13}
        SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
        SELF:ClientSize := System.Drawing.Size{391, 619}
        SELF:Controls:Add(SELF:panel1)
        SELF:Controls:Add(SELF:VesselNameLbl)
        SELF:Controls:Add(SELF:barDockControlLeft)
        SELF:Controls:Add(SELF:barDockControlRight)
        SELF:Controls:Add(SELF:barDockControlBottom)
        SELF:Controls:Add(SELF:barDockControlTop)
        SELF:HelpButton := true
        SELF:Name := "NewVoyageForm"
        SELF:ShowIcon := false
        SELF:StartPosition := System.Windows.Forms.FormStartPosition.CenterScreen
        SELF:Text := "Voyage Form"
        SELF:FormClosing += System.Windows.Forms.FormClosingEventHandler{ SELF, @NewVoyageForm_FormClosing() }
        SELF:FormClosed += System.Windows.Forms.FormClosedEventHandler{ SELF, @NewVoyageForm_FormClosed() }
        SELF:Shown += System.EventHandler{ SELF, @NewVoyageForm_Shown() }
        ((System.ComponentModel.ISupportInitialize)(SELF:barManager1)):EndInit()
        SELF:panel1:ResumeLayout(false)
        SELF:panel1:PerformLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:ToGC)):EndInit()
        SELF:ToGC:ResumeLayout(false)
        SELF:ToGC:PerformLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:PortDestinationDG)):EndInit()
        ((System.ComponentModel.ISupportInitialize)(SELF:FromGC)):EndInit()
        SELF:FromGC:ResumeLayout(false)
        SELF:FromGC:PerformLayout()
        ((System.ComponentModel.ISupportInitialize)(SELF:barAndDockingController1)):EndInit()
        SELF:ResumeLayout(false)
        SELF:PerformLayout()

        #endregion

END CLASS 
